<?php

/**
 * hook_form_alter
 * 
 * Set search block input placeholder copy
 */
function syd_tweaks_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_block_form') {
	  $form['keys']['#attributes']['placeholder'] = t('Search...');
  }
}

/**
 * Implements hook_theme().
 * 
 * Set theme tempalte for 'Emergency message' block
 */
function emergency_message() {
  return array(
    'emergency_message' => array(
      'variables' => array('title' => NULL, 'description' => NULL),
      'template' => 'block--emergency_message',
    ),
  );
}